In [2]:
print("Hello world")

Hello world

In [5]:
import pandas as pd

In [8]:
pd.DataFrame({'yes':[50, 21], 'no':[13,1]},index=['A', 'B'])

   yes  no
A   50  13
B   21   1

In [10]:
titanic=pd.read_csv("./train.csv")

In [11]:
titanic[['PassengerId', 'Pclass']]

     PassengerId  Pclass
0              1       3
1              2       1
2              3       3
3              4       1
4              5       3
..           ...     ...
886          887       2
887          888       1
888          889       3
889          890       1
890          891       3

[891 rows x 2 columns]

In [ ]:
titanic[10: 15, 0, 1]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
12,13,0,3,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,8.0500,NaN,S
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750,NaN,S
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542,NaN,S

In [ ]:
titanic.iloc[100:116]

10    female
11    female
12      male
13      male
14    female
Name: Sex, dtype: str

In [17]:
titanic.iloc[10: 15]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
12,13,0,3,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,8.0500,NaN,S
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750,NaN,S
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542,NaN,S

In [18]:
titanic.loc[10:15, ["PassengerId", "Sex"]]

    PassengerId     Sex
10           11  female
11           12  female
12           13    male
13           14    male
14           15  female
15           16  female

In [19]:
titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [21]:
titanic.Age <= 20

0      False
1      False
2      False
3      False
4      False
       ...
886    False
887     True
888    False
889    False
890    False
Name: Age, Length: 891, dtype: bool

In [22]:
titanic[titanic.Age <= 20]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
12,13,0,3,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,8.0500,NaN,S
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
869,870,1,3,"Johnson, Master. Harold Theodor",male,4.0,1,1,347742,11.1333,NaN,S
875,876,1,3,"Najib, Miss. Adele Kiamie ""Jane""",female,15.0,0,0,2667,7.2250,NaN,C
876,877,0,3,"Gustafsson, Mr. Alfred Ossian",male,20.0,0,0,7534,9.8458,NaN,S
877,878,0,3,"Petroff, Mr. Nedelio",male,19.0,0,0,349212,7.8958,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S

In [ ]:
titanic[titanic.Age <= 20]

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')

In [44]:
titanic[titanic.Sex == "Male"]

Empty DataFrame
Columns: [PassengerId, Survived, Pclass, Name, Sex, Age, SibSp, Parch, Ticket, Fare, Cabin, Embarked]
Index: []

In [26]:
titanic[(titanic.Age <= 20) & (titanic.Embarked=='s')]

Empty DataFrame
Columns: [PassengerId, Survived, Pclass, Name, Sex, Age, SibSp, Parch, Ticket, Fare, Cabin, Embarked]
Index: []

In [30]:
titanic[(titanic.Embarked.isin(['s', 'c']))]

Empty DataFrame
Columns: [PassengerId, Survived, Pclass, Name, Sex, Age, SibSp, Parch, Ticket, Fare, Cabin, Embarked]
Index: []

In [31]:
titanic.Age.isna()

0      False
1      False
2      False
3      False
4      False
       ...
886    False
887    False
888     True
889    False
890    False
Name: Age, Length: 891, dtype: bool

In [32]:
titanic[titanic.Age.isna()]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,7.2250,NaN,C
26,27,0,3,"Emir, Mr. Farred Chehab",male,NaN,0,0,2631,7.2250,NaN,C
28,29,1,3,"O'Dwyer, Miss. Ellen ""Nellie""",female,NaN,0,0,330959,7.8792,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...,...
859,860,0,3,"Razi, Mr. Raihed",male,NaN,0,0,2629,7.2292,NaN,C
863,864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,69.5500,NaN,S
868,869,0,3,"van Melkebeke, Mr. Philemon",male,NaN,0,0,345777,9.5000,NaN,S
878,879,0,3,"Laleff, Mr. Kristo",male,NaN,0,0,349217,7.8958,NaN,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S

In [34]:
titanic = titanic[titanic.Age.notnull()]

In [35]:
titanic.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,714.000000,714.000000,714.000000,714.000000,714.000000,714.000000,714.000000
mean,448.582633,0.406162,2.236695,29.699118,0.512605,0.431373,34.694514
std,259.119524,0.491460,0.838250,14.526497,0.929783,0.853289,52.918930
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,222.250000,0.000000,1.000000,20.125000,0.000000,0.000000,8.050000
50%,445.000000,0.000000,2.000000,28.000000,0.000000,0.000000,15.741700
75%,677.750000,1.000000,3.000000,38.000000,1.000000,1.000000,33.375000
max,891.000000,1.000000,3.000000,80.000000,5.000000,6.000000,512.329200

In [36]:
titanic.describe()['PassengerId']

count    714.000000
mean     448.582633
std      259.119524
min        1.000000
25%      222.250000
50%      445.000000
75%      677.750000
max      891.000000
Name: PassengerId, dtype: float64

In [39]:
titanic.keys()

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')

In [41]:
titanic.Survived.value_counts()

Survived
0    424
1    290
Name: count, dtype: int64

In [43]:
titanic.Sex.value_counts()

Sex
male      453
female    261
Name: count, dtype: int64

In [45]:
titanic.Name.map(lambda n : 'Je suis '+ n)

0                        Je suis Braund, Mr. Owen Harris
1      Je suis Cumings, Mrs. John Bradley (Florence B...
2                         Je suis Heikkinen, Miss. Laina
3      Je suis Futrelle, Mrs. Jacques Heath (Lily May...
4                       Je suis Allen, Mr. William Henry
                             ...
885         Je suis Rice, Mrs. William (Margaret Norton)
886                        Je suis Montvila, Rev. Juozas
887                 Je suis Graham, Miss. Margaret Edith
889                        Je suis Behr, Mr. Karl Howell
890                          Je suis Dooley, Mr. Patrick
Name: Name, Length: 714, dtype: str

In [46]:
titanic.Sex.map(lambda x: 1 if x == 'male' else 0)

0      1
1      0
2      0
3      0
4      1
      ..
885    0
886    1
887    0
889    1
890    1
Name: Sex, Length: 714, dtype: int64

In [47]:
titanic.Sex

0        male
1      female
2      female
3      female
4        male
        ...
885    female
886      male
887    female
889      male
890      male
Name: Sex, Length: 714, dtype: str

In [48]:
titanic['Sex_modif'] = titanic.Sex.map(lambda x: 1 if x == 'male' else 0)

In [50]:
titanic.Sex_modif

0      1
1      0
2      0
3      0
4      1
      ..
885    0
886    1
887    0
889    1
890    1
Name: Sex_modif, Length: 714, dtype: int64

In [53]:
def introduce(row):
	row['salutation'] = "Je suis "+row.Name+". J'ai "+str(row.Age)+" ans"
	return row

titanic.apply(introduce, axis="columns")['salutation']

0         Je suis Braund, Mr. Owen Harris. J'ai 22.0 ans
1      Je suis Cumings, Mrs. John Bradley (Florence B...
2          Je suis Heikkinen, Miss. Laina. J'ai 26.0 ans
3      Je suis Futrelle, Mrs. Jacques Heath (Lily May...
4        Je suis Allen, Mr. William Henry. J'ai 35.0 ans
                             ...
885    Je suis Rice, Mrs. William (Margaret Norton). ...
886         Je suis Montvila, Rev. Juozas. J'ai 27.0 ans
887    Je suis Graham, Miss. Margaret Edith. J'ai 19....
889         Je suis Behr, Mr. Karl Howell. J'ai 26.0 ans
890           Je suis Dooley, Mr. Patrick. J'ai 32.0 ans
Name: salutation, Length: 714, dtype: str

In [54]:
titanic.groupby(['Sex']).Age.min()

Sex
female    0.75
male      0.42
Name: Age, dtype: float64

In [56]:
titanic.groupby(['Sex', 'Embarked']).Age.mean()

Sex     Embarked
female  C           28.344262
        Q           24.291667
        S           27.771505
male    C           32.998841
        Q           30.937500
        S           30.291440
Name: Age, dtype: float64

In [57]:
titanic.groupby(['Embarked']).apply(lambda df: df.iloc[:3])

             PassengerId  Survived  Pclass  \
Embarked
C        1             2         1       1
         9            10         1       2
         30           31         0       1
Q        16           17         0       3
         22           23         1       3
         44           45         1       3
S        0             1         0       3
         2             3         1       3
         3             4         1       1

                                                          Name     Sex   Age  \
Embarked
C        1   Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0
         9                 Nasser, Mrs. Nicholas (Adele Achem)  female  14.0
         30                           Uruchurtu, Don. Manuel E    male  40.0
Q        16                               Rice, Master. Eugene    male   2.0
         22                        McGowan, Miss. Anna "Annie"  female  15.0
         44                      Devaney, Miss. Margaret Delia  female  19.0
S        0                             Braund, Mr. Owen Harris    male  22.0
         2                              Heikkinen, Miss. Laina  female  26.0
         3        Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0

             SibSp  Parch            Ticket     Fare Cabin  Sex_modif
Embarked
C        1       1      0          PC 17599  71.2833   C85          0
         9       1      0            237736  30.0708   NaN          0
         30      0      0          PC 17601  27.7208   NaN          1
Q        16      4      1            382652  29.1250   NaN          1
         22      0      0            330923   8.0292   NaN          0
         44      0      0            330958   7.8792   NaN          0
S        0       1      0         A/5 21171   7.2500   NaN          1
         2       0      0  STON/O2. 3101282   7.9250   NaN          0
         3       1      0            113803  53.1000  C123          0

In [ ]:
titanic.Sex.replace('male', 'm').replace('female', 'f')

0           m
1      female
2      female
3      female
4           m
        ...
885    female
886         m
887    female
889         m
890         m
Name: Sex, Length: 714, dtype: str

In [60]:
titanic.Sex.replace('male', 'm').replace('female', 'f')

0      m
1      f
2      f
3      f
4      m
      ..
885    f
886    m
887    f
889    m
890    m
Name: Sex, Length: 714, dtype: str

In [61]:
titanic.Sex

0        male
1      female
2      female
3      female
4        male
        ...
885    female
886      male
887    female
889      male
890      male
Name: Sex, Length: 714, dtype: str